import { TRAPS } from "@/config/traps.js";
import { ENEMIES } from "@/config/enemies.js";
import { DOORS } from "@/config/doors.js";
import { SWITCHES } from "@/config/switches.js";
import { ITEMS } from "@/config/items.js";
import { TELEPORTERS } from "@/config/teleporters.js";
import { NOTES } from "@/config/notes.js";
import { SPECIAL_TILES } from "@/config/specialTiles.js";

export const level4 = {
  specialTiles: [SPECIAL_TILES.water, SPECIAL_TILES.lava, SPECIAL_TILES.slime],
  sprites: {
    "#": "wall1",
    "▤": "wall6",
    "▉": "wall4",
    ".": "floor3",
    " ": "floor5a",
    _: "floor5b",
    "♒": "water1",
    "░": "lava",
    "▁": "slime",
  },
  exits: [
    { x: 19, y: 5, symbol: " ", color: " ", target: { levelIndex: 1, x: 0, y: 5 } },
    { x: 18, y: 18, symbol: ">", color: "stairsdown", target: { levelIndex: 4, x: 1, y: 1 } },
  ],
  decos: [
    { symbol: "☠", x: 16, y: 7, color: "corpse1" },
    { symbol: "☠", x: 4, y: 1, color: "corpse1" },
    { symbol: "O", x: 6, y: 5, color: "table" },
  ],
  name: "The Maze of Madness",
  data: [
    ["#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
    ["#", "▁", "▁", "▁", "▁", "▁", "▁", "▁", ".", ".", ".", ".", ".", "#", ".", ".", ".", ".", ".", "#"],
    ["#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", ".", "#", ".", "#", "#", "#", ".", "#"],
    ["#", ".", "░", "#", ".", ".", ".", "#", "░", ".", ".", "#", ".", "#", ".", ".", ".", "#", ".", "#"],
    ["#", ".", "░", "#", ".", "#", "#", "#", "#", ".", ".", ".", ".", "#", "#", "#", "#", "#", ".", "#"],
    ["#", ".", "░", "#", ".", "#", ".", ".", "#", ".", "#", "#", ".", "#", ".", ".", ".", ".", ".", "."],
    ["#", "#", "#", "#", ".", "#", "#", ".", "#", ".", "#", ".", ".", "#", ".", "#", "#", "#", ".", "#"],
    ["#", ".", ".", "#", ".", ".", ".", ".", "#", ".", "#", ".", ".", "#", ".", "#", ".", ".", ".", "#"],
    ["#", ".", ".", ".", "#", ".", "#", "#", "#", ".", "#", ".", ".", "#", ".", "#", ".", ".", ".", "#"],
    ["▤", "▤", "▤", ".", "#", ".", ".", ".", ".", ".", "#", "#", "#", "#", ".", "▉", "▉", "▉", "▉", "▉"],
    ["▤", ".", ".", ".", "#", "#", "#", "#", "#", ".", ".", ".", ".", ".", ".", "▉", ".", "▉", ".", "▉"],
    ["▤", ".", "▤", "#", "#", ".", "#", ".", "#", "#", "#", "#", ".", "#", ".", "▉", ".", "▉", ".", "▉"],
    ["▤", "▤", "▤", ".", ".", ".", "#", ".", ".", ".", ".", "#", ".", "#", ".", "#", ".", ".", ".", "#"],
    ["▤", "░", "▤", "#", "#", "#", "#", "#", "#", "#", "#", "#", ".", "#", ".", "#", "#", "#", ".", "#"],
    ["▤", ".", "▤", " ", " ", " ", " ", " ", "#", ".", ".", "#", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["▤", ".", "♒", " ", "#", "#", "#", " ", "#", ".", "#", "#", "#", "#", "#", "#", ".", "#", ".", "#"],
    ["▤", "▤", "▤", "▤", "#", ".", "#", ".", "#", ".", "#", ".", ".", ".", ".", "#", ".", "#", ".", "#"],
    ["▤", "♒", "♒", ".", ".", ".", ".", "#", "#", ".", "#", ".", "#", "#", "#", "#", ".", "#", ".", "#"],
    ["▤", "♒", "♒", "▤", ".", "#", ".", ".", ".", ".", ".", ".", "#", ".", ".", "#", ".", "#", ".", "#"],
    ["▤", "▤", "▤", "▤", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
  ],
  entities: {
    notes: [{ obj: NOTES.slimeynotice, x: 14, y: 0 }],
    doors: [
      { obj: DOORS.oakendoor, x: 18, y: 6, open: false },
      { obj: DOORS.rustydoor, x: 18, y: 4, open: false },
      { obj: DOORS.woodendoor, x: 14, y: 13, open: false },
      { obj: DOORS.oakendoor, x: 16, y: 11, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.woodendoor, x: 18, y: 11, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.woodendoor, x: 13, y: 10, open: false },
      { obj: DOORS.irondoor, x: 14, y: 2, open: false, key: ITEMS.ironkey },
      { obj: DOORS.woodendoor, x: 9, y: 7, open: false },
      { obj: DOORS.oakendoor, x: 11, y: 4, open: false },
      { obj: DOORS.woodendoor, x: 12, y: 5, open: false },
      { obj: DOORS.rustydoor, x: 8, y: 1, open: false },
      { obj: DOORS.irondoor, x: 8, y: 9, open: false },
      { obj: DOORS.woodendoor, x: 5, y: 8, open: false },
      { obj: DOORS.rustydoor, x: 9, y: 17, open: false },
      { obj: DOORS.oakendoor, x: 3, y: 17, open: false },
      { obj: DOORS.stonedoor, x: 18, y: 13, open: false },
      { obj: DOORS.irondoor, x: 17, y: 14, open: false },
      { obj: DOORS.goldendoor, x: 18, y: 16, open: false, key: ITEMS.goldkey },
    ],
    switches: [
      {
        obj: SWITCHES.plate,
        x: 14,
        y: 1,
        active: false,
        linked: [
          { x: 5, y: 9, tile: [".", "░"] },
          { x: 6, y: 9, tile: [".", "░"] },
          { x: 7, y: 9, tile: [".", "░"] },
          { x: 11, y: 6, tile: [".", "░"] },
          { x: 12, y: 6, tile: [".", "░"] },
          { x: 11, y: 7, tile: [".", "░"] },
          { x: 12, y: 7, tile: [".", "░"] },
          { x: 11, y: 8, tile: [".", "░"] },
          { x: 12, y: 8, tile: [".", "░"] },
        ],
      },
      { obj: SWITCHES.lever, x: 16, y: 10, active: false, linked: [{ x: 7, y: 10 }] },
      { obj: SWITCHES.lever, x: 1, y: 0, active: false, linked: [{ x: 0, y: 1 }] },
      { obj: SWITCHES.lever, x: 6, y: 3, active: false, linked: [{ x: 3, y: 7 }] },
      { obj: SWITCHES.plate, x: 1, y: 11, active: false, linked: [{ x: 1, y: 2 }] },
      { obj: SWITCHES.lever, x: 1, y: 5, active: false, linked: [{ x: 11, y: 14 }] },
      { obj: SWITCHES.lever, x: 0, y: 17, active: false, linked: [{ x: 12, y: 18 }] },
      { obj: SWITCHES.plate, x: 14, y: 18, active: false, linked: [{ x: 15, y: 16 }] },
    ],
    traps: [
      { obj: TRAPS.confusiontrap, x: 14, y: 6, active: true },
      { obj: TRAPS.archertrap, x: 0, y: 1, active: true },
      { obj: TRAPS.spiketrap, x: 1, y: 7, active: true },
      { obj: TRAPS.spiketrap, x: 2, y: 7, active: true },
      { obj: TRAPS.confusiontrap, x: 16, y: 16, active: true },
      { obj: TRAPS.poisentrap, x: 16, y: 18, active: true },
    ],
    enemies: [
      { obj: ENEMIES.ogre, x: 16, y: 8, loot: [ITEMS.bronzekey, ITEMS.lightgreypotion] },
      { obj: ENEMIES.greenslime, x: 12, y: 7 },
      { obj: ENEMIES.greenslime, x: 9, y: 1 },
      { obj: ENEMIES.greenslime, x: 11, y: 7 },
      { obj: ENEMIES.greenslime, x: 6, y: 9 },
      { obj: ENEMIES.greenslime, x: 18, y: 14, loot: [ITEMS.goldkey] },
      { obj: ENEMIES.rat, x: 9, y: 9 },
      { obj: ENEMIES.rat, x: 9, y: 10 },
      { obj: ENEMIES.rat, x: 10, y: 10 },
      { obj: ENEMIES.rat, x: 5, y: 17 },
      { obj: ENEMIES.rat, x: 6, y: 17 },
      { obj: ENEMIES.roach, x: 7, y: 18 },
      { obj: ENEMIES.roach, x: 8, y: 18 },
      { obj: ENEMIES.roach, x: 9, y: 18 },
      { obj: ENEMIES.roach, x: 10, y: 18 },
      { obj: ENEMIES.goblin, x: 10, y: 4, loot: [ITEMS.ironkey, ITEMS.darkredpotion] },
      { obj: ENEMIES.goblin, x: 1, y: 4, loot: [ITEMS.bookofswimming] },
      { obj: ENEMIES.skeleton, x: 4, y: 3, loot: [ITEMS.bronzekey] },
      { obj: ENEMIES.skeleton, x: 1, y: 10, loot: [ITEMS.scrollofturnundead, ITEMS.redpotion] },
      { obj: ENEMIES.skeleton, x: 18, y: 10, loot: [ITEMS.bookofdisarming] },
    ],
    items: [
      { obj: ITEMS.redpotion, x: 18, y: 8 },
      { obj: ITEMS.bluepotion, x: 18, y: 8 },
      { obj: ITEMS.scrollofmagiccloak, x: 16, y: 3 },
      { obj: ITEMS.broadsword, x: 7, y: 11 },
      { obj: ITEMS.leatherarmor, x: 7, y: 12 },
      { obj: ITEMS.redpotion, x: 9, y: 15 },
      { obj: ITEMS.lockpick, x: 10, y: 14 },
      { obj: ITEMS.scrolloffrostbite, x: 3, y: 12 },
      { obj: ITEMS.lightgreenpotion, x: 1, y: 8 },
      { obj: ITEMS.lightgreenpotion, x: 1, y: 8 },
      { obj: ITEMS.lightgreenpotion, x: 11, y: 16 },
      { obj: ITEMS.redpotion, x: 1, y: 8 },
      { obj: ITEMS.bluepotion, x: 1, y: 8 },
      { obj: ITEMS.darkredpotion, x: 1, y: 3 },
      { obj: ITEMS.bluepotion, x: 9, y: 3 },
      { obj: ITEMS.apple, x: 6, y: 5 },
      { obj: ITEMS.cheese, x: 6, y: 5 },
      { obj: ITEMS.meat, x: 6, y: 5 },
      { obj: ITEMS.stone, x: 12, y: 1 },
      { obj: ITEMS.stone, x: 3, y: 8 },
      { obj: ITEMS.stone, x: 5, y: 14 },
      { obj: ITEMS.darkredpotion, x: 3, y: 15, visible: false },
      { obj: ITEMS.darkbluepotion, x: 3, y: 15, visible: false },
    ],
  },
};
