import { TRAPS } from "@/config/traps.js";
import { ENEMIES } from "@/config/enemies.js";
import { DOORS } from "@/config/doors.js";
import { SWITCHES } from "@/config/switches.js";
import { ITEMS } from "@/config/items.js";
import { TELEPORTERS } from "@/config/teleporters.js";
import { NOTES } from "@/config/notes.js";
import { SPECIAL_TILES } from "@/config/specialTiles.js";


export const level2 = {
  specialTiles: [SPECIAL_TILES.lava],
  sprites: {
    "#": "wall4",
    "▤": "wall5",
    ".": "floor2",
    " ": "floor5a",
    _: "floor5b",
    "░": "lava",
  },
  exits: [
    {
      x: 17,
      y: 17,
      symbol: "<",
      color: "stairsup",
      target: { levelIndex: 0, x: 17, y: 14 },
    },
    {
      x: 0,
      y: 5,
      symbol: " ",
      color: " ",
      target: { levelIndex: 3, x: 19, y: 5 },
    },
    {
      x: 9,
      y: 0,
      symbol: " ",
      color: " ",
      target: { levelIndex: 2, x: 9, y: 19 },
    },
  ],
  decos: [
    { symbol: "*", x: 2, y: 2, color: "blood1" },
    { symbol: "*", x: 4, y: 2, color: "blood1" },
    { symbol: "☠", x: 12, y: 8, color: "corpse1" },
    { symbol: "☠", x: 14, y: 9, color: "corpse1" },
    { symbol: "☠", x: 14, y: 12, color: "corpse1" },
    { symbol: "O", x: 17, y: 1, color: "table" },
    { symbol: "☠", x: 10, y: 17, color: "corpse1" },
    { symbol: "O", x: 10, y: 16, color: "table" },
    { symbol: "*", x: 2, y: 10, color: "blood1" },
  ],
  name: "The Corridors of Chaos",
  data: [
    ["#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", "#", ".", ".", "#", ".", ".", ".", "#", ".", " ", ".", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", " ", " ", " ", " ", " ", " ", ".", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", "#", ".", ".", "#", ".", ".", ".", "#", ".", " ", ".", "#"],
    ["#", ".", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", " ", "▤", "#"],
    [".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "░", ".", ".", ".", ".", ".", ".", ".", "#"],
    ["#", ".", "▤", "▤", "▤", "▤", ".", "▤", "▤", " ", "▤", "▤", "▤", ".", "▤", "▤", "▤", ".", "▤", "#"],
    ["#", ".", ".", ".", "#", ".", ".", ".", "#", ".", "░", "#", " ", ".", " ", "#", ".", ".", ".", "#"],
    ["#", ".", ".", ".", "#", ".", ".", ".", "#", ".", "░", "#", " ", ".", " ", "#", ".", ".", ".", "#"],
    ["#", "#", "#", "#", "#", "#", " ", "#", "#", ".", "░", "#", " ", ".", " ", "#", ".", ".", ".", "#"],
    ["#", ".", ".", ".", "#", ".", ".", ".", "#", ".", "░", "#", " ", ".", " ", "#", "#", "#", "#", "#"],
    ["#", ".", ".", ".", "#", ".", ".", ".", "#", ".", "░", "#", " ", ".", " ", "#", ".", "#", ".", "#"],
    ["#", ".", ".", ".", "#", ".", ".", ".", "#", ".", "░", "#", " ", ".", " ", "#", ".", "#", ".", "#"],
    ["#", ".", "▤", "▤", "▤", "▤", ".", "▤", "▤", "▤", "▤", "▤", "▤", ".", "▤", "▤", ".", "▤", ".", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", ".", "░", ".", ".", ".", ".", ".", ".", ".", " ", ".", "#"],
    ["#", ".", "▤", "▤", ".", "▤", "▤", "▤", "▤", "▤", "▤", "▤", "▤", ".", "▤", "▤", "▤", " ", "▤", "#"],
    ["#", ".", ".", "#", ".", "#", " ", " ", "#", ".", ".", "#", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["#", ".", ".", "#", ".", " ", " ", " ", " ", ".", ".", "#", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["#", ".", ".", "#", ".", "#", " ", " ", "#", ".", ".", "#", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
  ],
  entities: {
    notes: [],
    teleporters: [],
    items: [
      { obj: ITEMS.stone, x: 17, y: 18 },
      { obj: ITEMS.stone, x: 15, y: 5 },
      { obj: ITEMS.stone, x: 14, y: 7 },
      { obj: ITEMS.stick, x: 6, y: 18 },
      { obj: ITEMS.stone, x: 6, y: 17 },
      { obj: ITEMS.redpotion, x: 16, y: 11 },
      { obj: ITEMS.darkbluepotion, x: 18, y: 11 },
      { obj: ITEMS.bronzekey, x: 13, y: 17 },
      { obj: ITEMS.bronzekey, x: 13, y: 3 },
      { obj: ITEMS.meat, x: 14, y: 11 },
      { obj: ITEMS.darkredpotion, x: 9, y: 10 },
      { obj: ITEMS.redpotion, x: 9, y: 10 },
      { obj: ITEMS.redpotion, x: 9, y: 10 },
      { obj: ITEMS.lightgreenpotion, x: 18, y: 2 },
      { obj: ITEMS.lightgreenpotion, x: 18, y: 2 },
      { obj: ITEMS.apple, x: 17, y: 1 },
      { obj: ITEMS.apple, x: 17, y: 1 },
      { obj: ITEMS.apple, x: 17, y: 1 },
      { obj: ITEMS.apple, x: 17, y: 1 },
      { obj: ITEMS.bluepotion, x: 9, y: 10 },
      { obj: ITEMS.cheese, x: 12, y: 10 },
      { obj: ITEMS.wornboots, x: 2, y: 1 },
      { obj: ITEMS.scrolloffirearrow, x: 10, y: 1 },
      { obj: ITEMS.scrolloffirearrow, x: 10, y: 1 },
      { obj: ITEMS.scrollofhealwounds1, x: 6, y: 11 },
      { obj: ITEMS.bookofdigging, x: 6, y: 2 },
      { obj: ITEMS.bookoflockpicking, x: 5, y: 8 },
      { obj: ITEMS.lockpick, x: 18, y: 8 },
      { obj: ITEMS.scrollofturnundead, x: 7, y: 17, visible: false },
    ],

    traps: [
      { obj: TRAPS.spiketrap, x: 13, y: 11, active: true },
      { obj: TRAPS.spiketrap, x: 13, y: 10, active: true },
      { obj: TRAPS.spiketrap, x: 13, y: 9, active: true },
      { obj: TRAPS.spiketrap, x: 13, y: 8, active: true },
      { obj: TRAPS.archertrap, x: 11, y: 9, active: true },
    ],
    enemies: [
      { obj: ENEMIES.goblin, x: 8, y: 14 },
      { obj: ENEMIES.goblin, x: 12, y: 16 },
      { obj: ENEMIES.goblin, x: 14, y: 16 },
      { obj: ENEMIES.rat, x: 16, y: 12 },
      { obj: ENEMIES.rat, x: 16, y: 12 },
      { obj: ENEMIES.rat, x: 6, y: 12 },
      { obj: ENEMIES.rat, x: 5, y: 12 },
      { obj: ENEMIES.rat, x: 5, y: 10 },
      { obj: ENEMIES.roach, x: 12, y: 14 },
      { obj: ENEMIES.roach, x: 13, y: 14 },
      { obj: ENEMIES.roach, x: 13, y: 14 },
      { obj: ENEMIES.roach, x: 10, y: 5 },
      { obj: ENEMIES.roach, x: 9, y: 5 },
      { obj: ENEMIES.roach, x: 7, y: 5 },
      { obj: ENEMIES.roach, x: 5, y: 5 },
      { obj: ENEMIES.roach, x: 5, y: 5 },
      { obj: ENEMIES.roach, x: 2, y: 5 },
      { obj: ENEMIES.zombie, x: 12, y: 3, loot: [ITEMS.redpotion, ITEMS.ironkey] },
      { obj: ENEMIES.zombie, x: 1, y: 11 },
      { obj: ENEMIES.ogre, x: 2, y: 2, loot: [ITEMS.bronzekey, ITEMS.redpotion] },
      { obj: ENEMIES.ogre, x: 5, y: 3 },
      { obj: ENEMIES.goblin, x: 17, y: 7, loot: [ITEMS.bronzekey, ITEMS.cheese] },
    ],
    doors: [
      { obj: DOORS.rustydoor, x: 17, y: 15, open: false },
      { obj: DOORS.woodendoor, x: 16, y: 13, open: false },
      { obj: DOORS.rustydoor, x: 18, y: 13, open: false },
      { obj: DOORS.woodendoor, x: 13, y: 15, open: false },
      { obj: DOORS.woodendoor, x: 13, y: 13, open: false },
      { obj: DOORS.rustydoor, x: 8, y: 17, open: false },
      { obj: DOORS.oakendoor, x: 5, y: 17, open: false },
      { obj: DOORS.woodendoor, x: 4, y: 15, open: false },
      { obj: DOORS.oakendoor, x: 6, y: 13, open: false },
      { obj: DOORS.irondoor, x: 6, y: 9, open: false },
      { obj: DOORS.woodendoor, x: 6, y: 6, open: false },
      { obj: DOORS.woodendoor, x: 9, y: 6, open: false },
      { obj: DOORS.oakendoor, x: 13, y: 6, open: false },
      { obj: DOORS.woodendoor, x: 17, y: 6, open: false },
      { obj: DOORS.rustydoor, x: 17, y: 4, open: false },
      { obj: DOORS.rustydoor, x: 15, y: 2, open: false },
      { obj: DOORS.woodendoor, x: 11, y: 2, open: false },
      { obj: DOORS.irondoor, x: 8, y: 2, open: false, key: ITEMS.ironkey },
      { obj: DOORS.oakendoor, x: 1, y: 15, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.woodendoor, x: 1, y: 13, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.woodendoor, x: 1, y: 6, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.woodendoor, x: 1, y: 4, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.irongate, x: 0, y: 5, open: false, locks: 4 },
    ],

    switches: [
      { obj: SWITCHES.plate, x: 1, y: 3, active: false, linked: [{ x: 0, y: 5 }] },
      { obj: SWITCHES.plate, x: 1, y: 7, active: false, linked: [{ x: 0, y: 5 }] },
      { obj: SWITCHES.plate, x: 1, y: 10, active: false, linked: [{ x: 0, y: 5 }] },
      { obj: SWITCHES.plate, x: 1, y: 18, active: false, linked: [{ x: 0, y: 5 }] },
      { obj: SWITCHES.woodenplate, x: 12, y: 12, active: false, linked: [{ x: 11, y: 9 }] },
      { obj: SWITCHES.lever, x: 13, y: 0, active: false, linked: [{ x: 9, y: 0 }] },
    ],
  },
};
