import { TRAPS } from "@/config/traps.js";
import { ENEMIES } from "@/config/enemies.js";
import { DOORS } from "@/config/doors.js";
import { SWITCHES } from "@/config/switches.js";
import { ITEMS } from "@/config/items.js";
import { TELEPORTERS } from "@/config/teleporters.js";
import { NOTES } from "@/config/notes.js";
import { SPECIAL_TILES } from "@/config/specialTiles.js";

export const level1 = {
  specialTiles: [SPECIAL_TILES.water],
  sprites: {
    "#": "wall4",
    ".": "floor1",
    " ": "floor5a",
    _: "floor5b",
    "♒": "water1",
  },
  exits: [
    {
      x: 17,
      y: 14,
      symbol: ">",
      color: "stairsdown",
      target: { levelIndex: 1, x: 17, y: 17 },
    },
  ],
  decos: [
    { symbol: "☠", x: 9, y: 2, color: "corpse1" },
    { symbol: "ʊ", x: 2, y: 3, color: "toilet" },
    { symbol: "*", x: 1, y: 3, color: "blood1" },
    { symbol: "ʊ", x: 4, y: 3, color: "toilet" },
    { symbol: "ʊ", x: 16, y: 3, color: "toilet" },
    { symbol: "ʊ", x: 14, y: 3, color: "toilet" },
    { symbol: "☠", x: 3, y: 7, color: "corpse1" },
    { symbol: "☠", x: 6, y: 6, color: "corpse1" },
    { symbol: "*", x: 6, y: 7, color: "blood1" },
    { symbol: "☠", x: 10, y: 12, color: "corpse1" },
    { symbol: "Ȋ", x: 8, y: 11, color: "pillar1", solid: true },
    { symbol: "Ȋ", x: 8, y: 14, color: "pillar1", solid: true },
    { symbol: "Ȋ", x: 7, y: 1, color: "pillar1", solid: true },
    { symbol: "Ȋ", x: 10, y: 1, color: "pillar1", solid: true },
  ],
  name: "The Cold Cells",
  data: [
    ["#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
    ["#", ".", ".", "#", ".", ".", "#", ".", ".", ".", ".", "#", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "#"],
    ["#", ".", ".", "#", ".", ".", "#", ".", ".", ".", ".", "#", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["#", "#", "#", "#", "#", "#", "#", ".", "#", "#", ".", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", "#", ".", ".", ".", "#", ".", ".", "#", ".", ".", ".", "#"],
    ["#", ".", " ", " ", " ", " ", " ", ".", "#", ".", ".", ".", "#", ".", ".", "#", ".", ".", ".", "#"],
    ["#", ".", " ", " ", " ", " ", " ", ".", "#", ".", ".", ".", "#", ".", ".", ".", ".", ".", ".", "#"],
    ["#", ".", " ", " ", " ", " ", " ", ".", "#", ".", ".", ".", ".", " ", ".", "#", ".", ".", ".", "#"],
    ["#", ".", ".", ".", ".", ".", ".", ".", "#", ".", ".", ".", "#", " ", ".", "#", "#", ".", "#", "#"],
    ["#", ".", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", " ", ".", "#", ".", ".", ".", "#"],
    ["#", ".", "#", "#", ".", ".", ".", ".", ".", "#", ".", ".", ".", " ", ".", "#", ".", ".", ".", "#"],
    ["#", ".", "#", ".", ".", ".", ".", ".", ".", ".", " ", " ", " ", " ", ".", "#", ".", ".", ".", "#"],
    ["#", ".", "#", ".", ".", ".", ".", ".", ".", "#", "♒", "♒", "♒", "♒", "♒", "#", ".", ".", ".", "#"],
    ["#", ".", "#", ".", ".", ".", ".", ".", ".", "#", ".", ".", ".", ".", ".", "#", ".", ".", ".", "#"],
    ["#", ".", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
    ["#", ".", ".", ".", ".", ".", "#", ".", ".", ".", ".", ".", "#", ".", ".", ".", ".", ".", ".", "#"],
    ["#", ".", "#", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", ".", "#"],
    ["#", ".", "#", ".", ".", ".", "#", ".", ".", ".", ".", ".", "#", ".", ".", ".", ".", ".", ".", "#"],
    ["#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#", "#"],
  ],
  entities: {
    notes: [{ obj: NOTES.crumpledpaper, x: 2, y: 2 }],
    teleporters: [{ obj: TELEPORTERS.blueteleporter, x: 4, y: 11, target: { x: 1, y: 9 }, active: false }],
    items: [
      { obj: ITEMS.rottenapple, x: 2, y: 1 },
      { obj: ITEMS.bread, x: 14, y: 5 },
      { obj: ITEMS.redpotion, x: 8, y: 2 },
      { obj: ITEMS.bread, x: 8, y: 2 },
      { obj: ITEMS.meat, x: 14, y: 5 },
      { obj: ITEMS.meat, x: 4, y: 16 },
      { obj: ITEMS.apple, x: 14, y: 5 },
      { obj: ITEMS.apple, x: 5, y: 16 },
      { obj: ITEMS.rustysword, x: 17, y: 2 },
      { obj: ITEMS.bronzekey, x: 5, y: 4, visible: false },
      { obj: ITEMS.redpotion, x: 5, y: 1 },
      { obj: ITEMS.redpotion, x: 5, y: 14 },
      { obj: ITEMS.redpotion, x: 15, y: 17 },
      { obj: ITEMS.redpotion, x: 15, y: 17 },
      { obj: ITEMS.lightgreypotion, x: 14, y: 1 },
      { obj: ITEMS.lightgreenpotion, x: 14, y: 6 },
      { obj: ITEMS.darkredpotion, x: 10, y: 7 },
      { obj: ITEMS.darkredpotion, x: 17, y: 18 },
      { obj: ITEMS.bluepotion, x: 10, y: 7 },
      { obj: ITEMS.bluepotion, x: 15, y: 16 },
      { obj: ITEMS.darkbluepotion, x: 18, y: 14 },
      { obj: ITEMS.blackpotion, x: 1, y: 9 },
      { obj: ITEMS.oldleatherarmor, x: 18, y: 8 },
      { obj: ITEMS.leathercap, x: 3, y: 14 },
      { obj: ITEMS.shovel, x: 14, y: 14 },
      { obj: ITEMS.scrollofturnundead, x: 1, y: 7 },
      { obj: ITEMS.scrollofhealwounds1, x: 7, y: 7 },
      { obj: ITEMS.scrolloffirearrow, x: 18, y: 3 },
      { obj: ITEMS.scrollofhealwounds1, x: 5, y: 7, visible: false },
      { obj: ITEMS.bookoffiretouch, x: 14, y: 17 },
    ],

    traps: [
      { obj: TRAPS.spiketrap, x: 7, y: 6, active: true },
      { obj: TRAPS.spiketrap, x: 7, y: 8, active: true },
      { obj: TRAPS.poisentrap, x: 10, y: 9, active: true },
      { obj: TRAPS.archertrap, x: 3, y: 11, active: true },
      { obj: TRAPS.archertrap, x: 19, y: 17, active: true },
      { obj: TRAPS.spiketrap, x: 17, y: 11, active: true },
      { obj: TRAPS.spiketrap, x: 17, y: 12, active: true },
      { obj: TRAPS.poisentrap, x: 4, y: 17, active: true },
    ],
    enemies: [
      { obj: ENEMIES.goblin, x: 13, y: 2, loot: [ITEMS.ironkey, ITEMS.apple] },
      { obj: ENEMIES.goblin, x: 17, y: 6, loot: [ITEMS.bronzekey] },
      { obj: ENEMIES.rat, x: 16, y: 1 },
      { obj: ENEMIES.rat, x: 10, y: 17 },
      { obj: ENEMIES.rat, x: 10, y: 16 },
      { obj: ENEMIES.rat, x: 9, y: 16 },
      { obj: ENEMIES.rat, x: 8, y: 18 },
      { obj: ENEMIES.rat, x: 18, y: 2 },
      { obj: ENEMIES.rat, x: 17, y: 3 },
      { obj: ENEMIES.rat, x: 14, y: 8 },
      { obj: ENEMIES.rat, x: 12, y: 12, loot: [ITEMS.redpotion] },
      { obj: ENEMIES.zombie, x: 4, y: 8, loot: [ITEMS.redpotion] },
      { obj: ENEMIES.zombie, x: 1, y: 5 },
      { obj: ENEMIES.ogre, x: 1, y: 12, loot: [ITEMS.goldkey] },
    ],
    doors: [
      { obj: DOORS.rustydoor, x: 3, y: 2, open: false, locks: 2 },
      { obj: DOORS.woodendoor, x: 6, y: 2, open: false },
      { obj: DOORS.woodendoor, x: 11, y: 2, open: false },
      { obj: DOORS.woodendoor, x: 15, y: 2, open: false, key: ITEMS.bronzekey },
      { obj: DOORS.irondoor, x: 7, y: 4, open: false },
      { obj: DOORS.irondoor, x: 10, y: 4, open: false, key: ITEMS.ironkey },
      { obj: DOORS.woodendoor, x: 12, y: 8, open: false },
      { obj: DOORS.woodendoor, x: 15, y: 7, open: false },
      { obj: DOORS.goldendoor, x: 17, y: 9, open: false, key: ITEMS.goldkey },
      { obj: DOORS.stonedoor, x: 12, y: 17, open: false, key: ITEMS.stonekey },
      { obj: DOORS.woodendoor, x: 6, y: 17, open: false },
      { obj: DOORS.woodendoor, x: 2, y: 16, open: false },
      { obj: DOORS.woodendoor, x: 1, y: 15, open: false },
      { obj: DOORS.woodendoor, x: 1, y: 10, open: false },
      { obj: DOORS.woodendoor, x: 9, y: 12, open: false, key: ITEMS.bronzekey },
    ],

    switches: [
      {
        obj: SWITCHES.lever,
        x: 0,
        y: 3,
        active: false,
        linked: [{ x: 3, y: 2 }],
      },
      {
        obj: SWITCHES.lever,
        x: 0,
        y: 1,
        active: false,
        linked: [{ x: 3, y: 2 }],
      },
      {
        obj: SWITCHES.lever,
        x: 13,
        y: 0,
        active: false,
        linked: [{ x: 4, y: 11 }],
      },
      {
        obj: SWITCHES.plate,
        x: 18,
        y: 5,
        active: false,
        linked: [{ x: 5, y: 4 }],
      },
      {
        obj: SWITCHES.plate,
        x: 1,
        y: 18,
        active: false,
        linked: [{ x: 12, y: 17 }],
      },
    ],
  },
};
