import { ATTACKS } from "./attacks.js";

export const ENEMIES = {
  goblin: {
    name: "Goblin",
    type: "creature",
    sprite: "goblin",
    hp: 5,
    ac: 1,
    view: 3,
    speed: 1,
    diagonal: false,
    attacks: [ATTACKS.slash, ATTACKS.stab, ATTACKS.stone],
    mobile: false,
    canPickPocket: 2,
    resistances: {
      fire: 0,
      water: 0,
      earth: 0,
      air: 0,
      physical: 0,
      poison: 0,
      bleeding: 0,
      confusion: 0,
      paralysis: 0,
      petrified: 0,
      blindness: 0,
    },
  },
  zombie: {
    name: "Zombie",
    type: "undead",
    sprite: "zombie",
    hp: 8,
    ac: 2,
    view: 3,
    speed: 2,
    diagonal: true,
    canPickPocket: 1,
    attacks: [ATTACKS.strike, ATTACKS.bite2],
    mobile: false,
    resistances: {
      fire: -100,
      water: 0,
      earth: 0,
      air: 0,
      physical: 0,
      poison: 0,
      bleeding: 0,
      confusion: 0,
      paralysis: 0,
      petrified: 0,
      blindness: 0,
    },
  },
  skeleton: {
    name: "Skeleton",
    type: "undead",
    sprite: "skeleton",
    hp: 8,
    ac: 3,
    view: 5,
    speed: 1,
    diagonal: true,
    canPickPocket: 1,
    attacks: [ATTACKS.strike, ATTACKS.slash, ATTACKS.stab, ATTACKS.doublestrike],
    mobile: true,
    resistances: {
      fire: -100,
      water: 0,
      earth: 0,
      air: 0,
      physical: 0,
      poison: 50,
      bleeding: 0,
      confusion: 0,
      paralysis: 0,
      petrified: 0,
      blindness: 0,
    },
  },
  ogre: {
    name: "Ogre",
    type: "creature",
    sprite: "ogre",
    hp: 10,
    ac: 4,
    view: 5,
    speed: 2,
    diagonal: false,
    attacks: [ATTACKS.strike, ATTACKS.smash, ATTACKS.stomp],
    mobile: true,
    canPickPocket: 1,
    resistances: {
      fire: 25,
      water: 0,
      earth: 0,
      air: 0,
      physical: 0,
      poison: 0,
      bleeding: 0,
      confusion: 50,
      paralysis: 25,
      petrified: 0,
      blindness: 0,
    },
  },
  rat: {
    name: "Rat",
    type: "beast",
    sprite: "rat",
    hp: 1,
    ac: 0,
    view: 5,
    speed: 1,
    diagonal: true,
    attacks: [ATTACKS.claw, ATTACKS.bite],
    mobile: true,
    resistances: {
      fire: 0,
      water: 0,
      earth: 0,
      air: 0,
      physical: 0,
      poison: 0,
      bleeding: 0,
      confusion: 0,
      paralysis: 0,
      petrified: 0,
      blindness: 0,
    },
  },
  roach: {
    name: "Roach",
    type: "insect",
    sprite: "roach",
    hp: 1,
    ac: 0,
    view: 5,
    speed: 1,
    diagonal: true,
    attacks: [ATTACKS.snap],
    mobile: true,
    resistances: {
      fire: 0,
      water: 0,
      earth: 0,
      air: 0,
      physical: 0,
      poison: 100,
      bleeding: 0,
      confusion: 0,
      paralysis: 0,
      petrified: 0,
      blindness: 0,
    },
  },
  greenslime: {
    name: "Green Slime",
    type: "ooze",
    sprite: "greenslime",
    hp: 3,
    ac: 0,
    view: 2,
    speed: 2,
    diagonal: true,
    attacks: [],
    mobile: true,
    resistances: {
      fire: 0,
      water: 0,
      earth: 0,
      air: 0,
      physical: 100,
      poison: 100,
      bleeding: 0,
      confusion: 0,
      paralysis: 0,
      petrified: 0,
      blindness: 0,
    },
  },
};
