export const ITEMS = {
  stone: {
    name: "Stone",
    sprite: "stone",
    type: "misc",
  },
  stick: {
    name: "Stick",
    sprite: "stick",
    type: "misc",
  },
  redpotion: {
    name: "Red Potion",
    sprite: "redpotion",
    type: "potion",
    stats: { hp: 5 },
  },
  darkredpotion: {
    name: "Dark Red Potion",
    sprite: "darkredpotion",
    type: "potion",
    maxStats: { hp: 1 },
  },
  bluepotion: {
    name: "Blue Potion",
    sprite: "bluepotion",
    type: "potion",
    stats: { mp: 5 },
  },
  darkbluepotion: {
    name: "Dark Blue Potion",
    sprite: "darkbluepotion",
    type: "potion",
    maxStats: { mp: 1 },
  },
  greenpotion: {
    name: "Green Potion",
    sprite: "greenpotion",
    type: "potion",
    stats: { stm: 5 },
  },
  lightgreenpotion: {
    name: "Light Green Potion",
    sprite: "lightgreenpotion",
    type: "potion",
    cure: ["Poison"],
  },
  blackpotion: {
    name: "Black Potion",
    sprite: "blackpotion",
    type: "potion",
    conditions: [{ name: "Blindness", duration: 10, color: "darkgrey" }],
  },
  lightgreypotion: {
    name: "Light Grey Potion",
    sprite: "lightgreypotion",
    type: "potion",
    conditions: [{ name: "Stone Skin", duration: 10, color: "lightgrey" }],
  },
  scrollofhealwounds1: {
    name: "Scroll of Healing",
    sprite: "scroll1",
    type: "scroll",
    cast: "healwounds1",
  },
  scrolloffrostbite: {
    name: "Scroll of Frostbite",
    sprite: "scroll2",
    type: "scroll",
    cast: "frostbite",
  },
  scrollofturnundead: {
    name: "Scroll of Turn Undead",
    sprite: "scroll2",
    type: "scroll",
    cast: "turnundead",
  },
  scrolloffirearrow: {
    name: "Scroll of Fire Arrow",
    sprite: "scroll3",
    type: "scroll",
    cast: "firearrow",
  },
  scrollofmagiccloak: {
    name: "Scroll of Magic Cloak",
    sprite: "scroll4",
    type: "scroll",
    cast: "magiccloak",
  },
  bronzekey: {
    name: "Bronze Key",
    sprite: "bronzekey",
    type: "key",
  },
  ironkey: {
    name: "Iron Key",
    sprite: "ironkey",
    type: "key",
  },
  goldkey: {
    name: "Gold Key",
    sprite: "goldenkey",
    type: "key",
  },
  stonekey: {
    name: "Stone Key",
    sprite: "stonekey",
    type: "key",
  },
  bread: {
    name: "Bread",
    sprite: "bread",
    type: "food",
    food: 20,
  },
  meat: {
    name: "Meat",
    sprite: "meat",
    type: "food",
    food: 25,
  },
  cheese: {
    name: "Cheese",
    sprite: "cheese",
    type: "food",
    food: 15,
  },
  rottenmeat: {
    name: "Rotten Meat",
    sprite: "rottenmeat",
    type: "food",
    food: -20,
    conditions: [{ name: "Poison", duration: 5, color: "green" }],
  },
  apple: {
    name: "Apple",
    sprite: "apple1",
    type: "food",
    food: 10,
  },
  rottenapple: {
    name: "Rotten Apple",
    sprite: "rottenapple",
    type: "food",
    food: -5,
    conditions: [{ name: "Poison", duration: 5, color: "green" }],
  },
  lockpick: {
    name: "Lockpick",
    sprite: "lockpick",
    type: "tool",
    functionality: "unlock",
  },
  disarmkit: {
    name: "Disarm Kit",
    sprite: "trapdisarmkit",
    type: "tool",
    functionality: "disarm",
  },
  shovel: {
    name: "Shovel",
    sprite: "shovel",
    type: "tool",
    functionality: "dig",
    durability: 10,
  },
  pickaxe: {
    name: "Pickaxe",
    sprite: "pickaxe",
    type: "tool",
    functionality: "mining",
    durability: 10,
  },
  rustysword: {
    name: "Rusty Old Sword",
    sprite: "rustysword",
    type: "weapon",
    stats: { dmg: [1, 4, 0] },
    slot: "weapon",
    weaponType: "melee",
  },
  broadsword: {
    name: "Broadsword",
    sprite: "broadsword",
    type: "weapon",
    stats: { dmg: [1, 8, 0] },
    slot: "weapon",
    weaponType: "melee",
  },
  bow: {
    name: "Bow",
    sprite: "bow",
    type: "weapon",
    stats: { dmg: [1, 4, 1] },
    slot: "weapon",
    weaponType: "ranged",
    range: 5,
  },
  oldleatherarmor: {
    name: "Old Leather Armor",
    sprite: "leatherarmor",
    type: "armor",
    slot: "body",
    ac: 1,
  },
  leatherarmor: {
    name: "Leather Armor",
    sprite: "leatherarmor2",
    type: "armor",
    slot: "body",
    ac: 2,
  },
  wornboots: {
    name: "Worn Boots",
    sprite: "leatherboots",
    type: "armor",
    slot: "feet",
    ac: 1,
  },
  leathercap: {
    name: "Leather Cap",
    sprite: "leathercap",
    type: "armor",
    slot: "head",
    ac: 1,
  },
  bookofdisarming: {
    name: "Book of Disarming Traps",
    sprite: "book3",
    type: "readable",
    learn: ["Disarm"],
  },
  bookoflockpicking: {
    name: "Book of Lockpicking",
    sprite: "book1",
    type: "readable",
    learn: ["Lockpicking"],
  },
  bookofmining: {
    name: "Book of Mining",
    sprite: "book2",
    type: "readable",
    learn: ["Mining"],
  },
  bookofswimming: {
    name: "Book of Swimming",
    sprite: "book3",
    type: "readable",
    learn: ["Swimming"],
  },
  bookofdigging: {
    name: "Book of Digging",
    sprite: "book3",
    type: "readable",
    learn: ["Digging"],
  },
  bookoffiretouch: {
    name: "Book of Firetouch",
    sprite: "book1",
    type: "readable",
    learn: ["firetouch"],
  },
  bookofdoublestrike: {
    name: "Book of Double Strike",
    sprite: "book2",
    type: "readable",
    learn: ["doublestrike"],
  },
};
