import { Condition } from "@/classes/Condition.js";

export const SPELLS = {
  firetouch: {
    name: "Fire Touch",
    sprite: "",
    color: "orangered",
    type: "spell",
    aoe: 1,
    singleTarget: true,
    cost: 3,
    hits: 1,
    extra: { fire: 5 },
    conditions: [new Condition(null, "Burning", 4, "orangered", 0.25)],
  },
  firearrow: {
    name: "Fire Arrow",
    sprite: "",
    color: "orangered",
    type: "spell",
    aoe: 5,
    singleTarget: true,
    cost: 5,
    hits: 1,
    extra: { fire: 7 },
    conditions: [new Condition(null, "Burning", 2, "orangered", 0.25)],
  },
  poisencloud: {
    name: "Poison Cloud",
    sprite: "",
    color: "green",
    type: "spell",
    aoe: 2,
    singleTarget: false,
    cost: 7,
    hits: 1,
    conditions: [new Condition(null, "Poison", 5, "green", 1)],
  },
  frostbite: {
    name: "Frostbite",
    sprite: "",
    color: "lightblue",
    type: "spell",
    aoe: 1,
    singleTarget: true,
    cost: 5,
    hits: 1,
    extra: { water: 5 },
    conditions: [new Condition(null, "Paralysis", 3, "lightblue", 0.25)],
  },
  elementalshield: {
    name: "Elemental Shield",
    sprite: "",
    color: "pink",
    type: "spell",
    aoe: 0,
    singleTarget: true,
    cost: 8,
    hits: 0,
    conditions: [
      new Condition(null, "Fire Shield", 5, "orangered", 1),
      new Condition(null, "Water Shield", 5, "lightblue", 1),
      new Condition(null, "Earth Shield", 5, "saddlebrown", 1),
      new Condition(null, "Air Shield", 5, "lightgray", 1),
    ],
  },
  turnundead: {
    name: "Turn Undead",
    sprite: "",
    color: "yellow",
    type: "spell",
    aoe: 3,
    singleTarget: false,
    cost: 10,
    hits: 1,
    stats: { dmg: [1, 10, 0] },
    typeBasedDamage: { undead: 3 },
    conditions: [],
  },
  healwounds1: {
    name: "Heal Minor Wounds",
    sprite: "",
    color: "lightgreen",
    type: "spell",
    aoe: 0,
    singleTarget: true,
    cost: 6,
    hits: 0,
    stats: { hp: 5 },
    conditions: [],
  },
  doublestrike: {
    name: "Double Strike",
    sprite: "",
    color: "lightblue",
    type: "special",
    aoe: 1,
    singleTarget: true,
    hits: 2,
    cost: 8,
    stats: { dmg: [1, 4, 0] },
  },
  cleave: {
    name: "Cleave",
    sprite: "",
    color: "orangered",
    type: "special",
    aoe: 1,
    singleTarget: false,
    hits: 1,
    cost: 10,
    stats: { dmg: [1, 6, 0] },
  },
  magiccloak: {
    name: "Magic Cloak",
    sprite: "",
    color: "lightblue",
    type: "spell",
    aoe: 0,
    singleTarget: true,
    cost: 5,
    hits: 0,
    conditions: [new Condition(null, "Invisibility", 10, "lightblue", 1)],
  },
  magiceye: {
    name: "Magic Eye",
    sprite: "",
    color: "lightblue",
    type: "spell",
    aoe: 0,
    singleTarget: true,
    cost: 10,
    hits: 0,
    conditions: [new Condition(null, "Magic Eye", 5, "lightblue", 1)],
  },
};
